parameters:
#    zmb_hello.example.class: ZMB\HelloBundle\Example

services:
#    zmb_hello.example:
#        class: %zmb_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
